### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Krish-Na-Pal** [sulejmanhoxha/shadcn-project-vite#1]
I have same issue.
how to run shadcn with javascript??

**Comment by sulejmanhoxha** [comment]
@Krish-Na-Pal  I have just updated the repository for you. there are two branches now:
- main - uses typescript
- javascript - uses javascript

In the javascript branch you can create js, jsx files and it will work fine but still the compoennts from shadcn will all be using typescript. if you see any error from typescript you can probably just ignore them. also make sure when you copy/paste code from shadcn (from the examples when you view a component) that you remove typescript annotations yourself.You can use typescript in the javascript branch aswell, but if you are going to use typescript than the main branch is better. Hope this helps :D.
